// Generated by CoffeeScript 1.6.1
(function() {
  var board, game, player;

  board = new App.Board(800, 600);

  player = new App.Player(400, 300, 2);

  game = new App.Game(board, player);

  document.body.appendChild(game.create);

  requestAnimationFrame(game.animate);

}).call(this);
