// Generated by CoffeeScript 1.6.1
(function() {

  App.Player = (function() {

    function Player(positionX, positionY, scale) {
      var playerTexture;
      this.positionX = positionX;
      this.positionY = positionY;
      this.scale = scale;
      this.sprite = 'img/bunny.png';
      playerTexture = PIXI.Texture.fromImage(this.sprite);
      this.pixiPlayer = PIXI.Sprite(playerTexture)["new"];
      this.pixiPlayer.anchor = PIXI.Point(0.5, 0.5)["new"];
      this.pixiPlayer.position.x = this.positionX;
      this.pixiPlayer.position.y = this.positionY;
      this.pixiPlayer.scale.x = this.scale;
      this.pixiPlayer.scale.y = this.scale;
    }

    Player.prototype.moveTo = function(positionX, positionY) {
      this.positionX = positionX;
      this.positionY = positionY;
    };

    Player.prototype.rotation = function(deg) {
      return this.pixiPlayer.rotation += deg;
    };

    Player.prototype.position = function() {
      return {
        x: this.positionX,
        y: this.positionY
      };
    };

    return Player;

  })();

}).call(this);
