// Generated by CoffeeScript 1.6.1
(function() {

  App.Board = (function() {

    function Board(width, height) {
      this.width = width;
      this.height = height;
      this.zombieGroups = {};
      this.renderer = PIXI.autoDetectRenderer(this.width, this.height)["new"];
      this.stage = new PIXI.Stage;
      window.Board = Board;
    }

    Board.prototype.addPlayer = function(player) {
      this.player = player;
      return this.stage.addChild(this.player.pixiPlayer);
    };

    Board.prototype.addGroupOfZombies = function(group) {
      return this.zombieGroups[group.name] = group;
    };

    Board.prototype.removeGroupOfZombies = function(group) {
      return delete this.zombieGroups[group.name];
    };

    Board.prototype.render = function() {
      return this.renderer.render(this.stage);
    };

    Board.prototype.init = function() {
      return renderer.view;
    };

    return Board;

  })();

}).call(this);
