// Generated by CoffeeScript 1.6.1
(function() {

  App.Game = (function() {

    function Game(board, player) {
      this.board = board;
      this.player = player;
      this.board.addPlayer(this.player);
    }

    Game.prototype.create = function() {
      return this.board.draw;
    };

    Game.prototype.animate = function() {
      this.player.rotation += 0.01;
      this.board.render;
      return requestAnimationFrame(this.animate());
    };

    return Game;

  })();

}).call(this);
